export const LOGO_ID = "67eeb1fcfaf070cbfb48da8c";
// export const LANDING_IMAGE_ID = "681720d16f814e4b889a247a"; // FIXME: solve cropping issue
export const RAZORPAY_IMAGE_ID = "6817211e6f814e4b889a247f";
export const ERROR_IMAGE_ID = "6817218c6f814e4b889a2483";
export const CATEGORIES = [
  "Smartphones",
  "Laptops",
  "Computers",
  "Cameras",
  "TVs",
  "Tablets",
  "Smartwatches",
  "Earphones & Headphones",
  "Gaming Consoles",
  "Processors (CPU)",
  "Graphics Cards (GPU)",
  "RAM",
  "Motherboards",
  "Storage (SSD / HDD)",
  "Power Supplies",
  "Computer Cases",
  "Monitors",
  "Keyboards",
  "Mice",
  "Webcams",
  "Speakers",
  "Printers & Scanners",
  "Mobile Accessories",
  "Laptop Accessories",
  "Cables & Chargers",
  "Screen Protectors",
  "Bags & Sleeves",
  "Mounts & Stands",
  "Smart Home Devices",
  "Wi-Fi Routers",
  "Smart Lights",
  "Security Cameras",
  "Voice Assistants",
  "Tech Repair Tools",
  "Cooling & Thermal Paste",
  "Cleaning Kits",
  "Cable Management",
];
