services:
  frontend:
    build: ./frontend
    container_name: techkart-frontend
    ports:
      - "80:4173"
    env_file:
      - ./frontend/.env
    command: pnpm run preview

  backend:
    build: ./backend
    container_name: techkart-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    command: npm run start
    depends_on:
      - redis
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/test/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:alpine
    container_name: techkart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo
    container_name: techkart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data

volumes:
  redis_data:
  mongo_data:
