services:
  frontend:
    build:
      context: ./frontend
      args:
        BUILD: "false"
    container_name: techkart-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    command: pnpm run dev

  backend:
    build:
      context: ./backend
      args:
        BUILD: "false"
    container_name: techkart-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npm run dev
    networks:
      - mongo-net
      - default
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/test/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  redis:
    image: redis:alpine
    container_name: techkart-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  mongo-net:
    external: true
